### ISSUE TITLE
Error: Connection failed

### ISSUE THREAD

**Issue by klausklebers** [urwolfiii/remote_py#3]
If i start the script it will not connect, it gives me the following errors:

`Traceback (most recent call last):
  File "*************", line 14, in <module>
    s.connect((ip, port))
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**", line 16, in <module>
    raise RuntimeError('Error: Connection failed')
RuntimeError: Error: Connection failed`

**Comment by urwolfiii** [comment]
Did you give the IP address of the server (python .\client_server  %ip%)
PS Make sure the server script is running

**Comment by klausklebers** [comment]
Thank you!
